import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import portfolioStyles from '../styles/Portfolio.module.css';
import Navbar from '../components/Navbar';

const portfolio = ({ images }) => {
  return (
    <>
      <Head>
        <title>Visual Crate | Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <script src='https://kit.fontawesome.com/84047fdc96.js' crossOrigin='anonymous'></script>
      </Head>

      <div className={portfolioStyles.headerContainer}>
        <Navbar />
        <div className={portfolioStyles.header}>
          <h1>Moments are meant to be captured, and that is what we intend to do. Hope you like them</h1>
        </div>
      </div>
      {/* Header end */}
      <div id={portfolioStyles.portfolio}>
        <div className={portfolioStyles.images}>
          {images.map((image) => {
            return (
              <div className={portfolioStyles.image} key={image.id}>
                <a href={image.image} target='_blank' rel='noopener noreferrer' className={portfolioStyles.expand}>
                  <Image src={image.image} alt='Image' width={image.width} height={image.height} objectFit='contain' />
                </a>
              </div>
            );
          })}
        </div>
      </div>
      <div className='footer'>
        <span>Copyright &#169; {new Date().getFullYear()}, Visual Crate</span>
        <span>
          Designed and Developed by{' '}
          <a href='http://joshuacoutinho.com' target='_blank' rel='noopener noreferrer' className='accent'>
            Joshua Coutinho
          </a>
        </span>
      </div>
    </>
  );
};

export async function getStaticProps() {
  const params = {
    expression: 'folder="test"',
  };
  const paramString = Object.keys(params)
    .map((key) => `${key}=${encodeURIComponent(params[key])}`)
    .join('&');
  const results = await fetch(`https://api.cloudinary.com/v1_1/${process.env.CLOUDINARY_CLOUD_NAME}/resources/search?${paramString}`, {
    headers: {
      Authorization: `Basic ${Buffer.from(process.env.CLOUDINARY_API_KEY + ':' + process.env.CLOUDINARY_API_SECRET).toString('base64')}`,
    },
  }).then((r) => r.json());

  const { resources } = results;

  const images = resources.map((resource) => {
    const { width, height } = resource;
    return {
      id: resource.asset_id,
      title: resource.public_id,
      image: resource.secure_url,
      width,
      height,
    };
  });

  return {
    props: {
      images,
    },
  };
}
export default portfolio;
